apiVersion: v1
kind: Service
metadata:
  name: uservice-status
  labels:
    name: uservice-status
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    name: uservice-status
